<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Ashok" name="com.vtg.auto.vtghometestnew.VTGHomeTest" tests="4" failures="1" timestamp="2023-02-04T15:02:49 IST" time="19.210" errors="0">
  <testcase name="VerifyLoginTest3" time="4.927" classname="com.vtg.auto.vtghometestnew.VTGHomeTest"/>
  <system-out/>
  <testcase name="VerifyLoginTest1" time="4.014" classname="com.vtg.auto.vtghometestnew.VTGHomeTest">
    <failure type="java.lang.AssertionError" message="expected [Login - JIVIEWS] but found [Google]">
      <![CDATA[java.lang.AssertionError: expected [Login - JIVIEWS] but found [Google]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.vtg.auto.vtghometestnew.VTGHomeTest.VerifyLoginTest1(VTGHomeTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- VerifyLoginTest1 -->
  <system-out/>
  <testcase name="VerifyLoginTest2" time="6.336" classname="com.vtg.auto.vtghometestnew.VTGHomeTest"/>
  <system-out/>
  <testcase name="VerifyLoginTest4" time="3.933" classname="com.vtg.auto.vtghometestnew.VTGHomeTest"/>
  <system-out/>
</testsuite> <!-- com.vtg.auto.vtghometestnew.VTGHomeTest -->
